import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
export const gStyle = StyleSheet.create({
  Course1:{
    backgroundColor:'lightgreen',
    padding:40,
    marginVertical:400,
    marginLeft:100,
    width:'50%',
    borderRadius:20,
    fontSize:14,
  },
  title:{
    flex:3,
    backgroundColor:'lightblue',

  },
  container:{
    flex:1,
    backgroundColor:'lightyellow',
    alignItems:'center',
  },
  sigmoid:{
    fontSize:24,
    fontWeight:'bold',
  },
  Intro:{
    width:300,
    backgroundColor:'lightgreen',
    marginBottom:10,
    borderRadius:10,
    alignItems:'center',
    justifyContent:'center',
  },
  info:{
    fontSize:16,
    marginTop:10,
  },
  forCharkas:{
    fontWeight:'bold',
    backgroundColor: 'lightblue',
    width: 220,
    height:50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginVertical: 8,
    paddingHorizontal:15,
    paddingVertical:10,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 3,
    elevation: 5,
  },
  forButtons:{
    fontWeight:'bold',
    backgroundColor: 'lightblue',
    width: '80%',
    minHeight: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginVertical: 8,
    paddingHorizontal:15,
    paddingVertical:10,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 3,
    elevation: 5,
    alignSelf:'flex-start',
  },
  scrollView: {
    flex: 1,
  },
  scrollContainer: {
    alignItems: 'center',
    paddingBottom: 20,
  },
  newTitle:{
    flex:1,
    alignContent:'center',
    alignItems:'center',
    justifyContent:'center',
    backgroundColor:'#F5F5DC',
  },
  homeButtons: {
    alignSelf:'flex-start',
    marginLeft:40,
    flexDirection:'column',
  },  
  charkism:{
    fontSize:12,
    fontWeight:'bold',
  },
  TypeShit:{
    fontSize:36,
    fontWeight:'bold',
    fontFamily:'arial',
    paddingBottom:80,
  },
  SendingImage:{
    width:20,
    height:20,
    borderRadius:10,
    marginLeft:10,
  },
  buttonContent:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'flex-start',
    width:'100%'
  },
  lessonBox:{
    backgroundColor:'white',
    padding:20,
    margin:20,
    borderRadius:10,
    shadowColor:'#000',
    shadowOffset:{width:0,height:2},
    shadowOpacity:0.3,
    shadowRadius:6,
  },
  lessonTitle:{
    fontSize:14,
    fontWeight:'bold',
    color:'#2a9d8f',
    marginBottom:10,
  },
  lessonTitle1:{
    backgroundColor:'lightgreen',
    padding:20,
    margin:20,
    borderRadius:10,
    fontSize:15,
    fontWeight:'bold',
    color:'gray',
    marginBottom:10,
  },
  codeBlock:{
    backgroundColor:'#E8E8E8',
    borderRadius:10,
    padding:10,
    marginTop:10,
    fontFamily:'Courier',
    fontSize:14,
    color:'#333',
  },
  lessonCodeBlock:{
    backgroundColor:'gray',
    padding:20,
    margin:20,
    borderRadius:10,
    shadowColor:'#000',
    shadowOffset:{width:0,height:2},
    shadowOpacity:0.3,
    shadowRadius:5,
  },
  topicBlock:{
    width:'90%',
    backgroundColor:'#f0f0f0',
    borderRadius:15,
    padding:10,
    shadowColor:'#000',
    shadowOffset:{width:0,height:3},
    shadowOpacity:0.3,
    shadowRadius:5,
  },
  topicHeader:{
    paddingVertical:10,
    paddingHorizontal:10,
    backgroundColor:'#4a90e2',
    borderRadius:10,
  },
  topicTitle:{
    fontSize:28,
    fontWeight:'bold',
    color:'white',
  },
  topicContent:{
    marginTop:10,
  },
  lessonText:{
    fontSize:16,
    color:'#333',
    marginBottom:10,
    fontWeight:'bold',
    backgroundColor: 'lightgreen',
    width: '110%',
    minHeight: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginVertical: 8,
    paddingHorizontal:15,
    paddingVertical:10,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 3,
    alignSelf:'flex-start',
  },
})
